### ISSUE TITLE
[BUG] A fatal error occurred while downloading the course.

### ISSUE THREAD

**Issue by ehsanzalian** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#108]
At the end of downloading courses, this error shows up:
![fatal error](https://github.com/ahmedayman4a/Linkedin-Learning-Courses-Downloader/assets/167192717/b83e41ba-56ae-4232-be18-23b8a496ed22)
I think this error occurs when downloading exercise files because when I check the downloaded folder, the exercise file has 0 bytes size and when I want to open the file, it shows corrupted file error.
Can you please help me with that? 

**Operating System**
 [Windows 10 Version 22H2]

**Log File**
2024-04-16 13:05:38.687 +03:30 [INF] Validating Input
2024-04-16 13:05:41.109 +03:30 [INF] Input Valid
2024-04-16 13:36:05.743 +03:30 [ERR] An fatal error occured while downloading the course
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.UriFormatException: Invalid URI: The URI is empty.
   at LLCD.DownloaderGUI.DownloaderForm.<DownloadCourse>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LLCD.DownloaderGUI.DownloaderForm.<DownloaderForm_Load>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at LLCD.DownloaderGUI.MainForm.<ExtractAndDownloadAsync>d__6.MoveNext()

**Comment by ViktoriaGit** [comment]
I get the same problem.

**Comment by firatsarlar** [comment]
Same problem. It is about exercise files download I think .

**Comment by achira7** [comment]
I get the same problem but only with some courses.
