### ISSUE TITLE
[BUG] Failed to download exerciseFile with name <filename>.zip

### ISSUE THREAD

**Issue by maintain3r** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#116]
**Describe the bug**

**Operating System**
 [e.g. Windows 10]

**Log File**
Upload the latest log file present at `%localappdata%\Linkedin-Learning-Courses-Downloader\app-1.1.0\logs` here.

Hello,
I'd like to report an issue that happens when I try to download a course.
I don;t know if this project is still maintained, hope it is as it's the best projects I've found on Internet.
When downloading a course it starts and goes well, fetches about 200megs of data and then fails, then the retry logic tries to download from where it's failed. Here's a piece of log of the app:
[ERR] Failed to download exerciseFile with name archivefilename.zip
System.AggregateException: One or more errors occurred. (Name or service not known (lilcdn-a.akamaihd.net:443))
 ---> System.Net.WebException: Name or service not known (lilcdn-a.akamaihd.net:443)
 ---> System.Net.Http.HttpRequestException: Name or service not known (lilcdn-a.akamaihd.net:443)
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.GetWebResponseTaskAsync(WebRequest request)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at LLCD.DownloaderTUI.CourseDownloader.<>c__DisplayClass13_0.<DownloadExerciseFile>b__0()
   at LLCD.CourseExtractor.Retry.<>c__DisplayClass2_0.<Do>b__0()
   at LLCD.CourseExtractor.Retry.Do[T](Func`1 function, String exceptionMessage, Action actionOnError, Action actionOnFatal, Int32 retries)
2024-11-08 17:10:05.313 -05:00 [INF] Running Action on Error
2024-11-08 17:10:05.313 -05:00 [ERR] Trying again ,5
2024-11-08 17:10:05.313 -05:00 [FTL] Error occured 5 times without being resolved
2024-11-08 17:10:05.320 -05:00 [ERR] Error while Downloading
System.Exception: A fatal error occured in the program. Check the logs for more info
   at LLCD.CourseExtractor.Retry.Do[T](Func`1 function, String exceptionMessage, Action actionOnError, Action actionOnFatal, Int32 retries)
   at LLCD.CourseExtractor.Retry.Do(Action function, String exceptionMessage, Action actionOnError, Action actionOnFatal, Int32 retries)
   at LLCD.DownloaderTUI.CourseDownloader.DownloadExerciseFile(DirectoryInfo courseDirectory, ProgressBar pbarCourse, ExerciseFile exerciseFile)
   at LLCD.DownloaderTUI.CourseDownloader.DownloadCourse(Course course, DirectoryInfo courseRootDirectory)
   
   Please help.

**Comment by moshin34** [comment]
I seem to have this same error from MacOS CLI.   Downloading all the videos, but failing to download the exercise files.
