### ISSUE TITLE
[BUG] Versions 1.1 and 1.2 Crashing on Cookie Import from Chrome

### ISSUE THREAD

**Issue by makehillflat** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#25]
**Describe the bug**
I'll just detail the issue with 1.1.0 for the moment. The same thing appears to be hapening with 2.0. The app crashes on importing cookies from Chrome. I don't have a problem importing from Firefox with 1.1.0.

**OS**
Windows 10 Pro 64 (19041.1415)

**Log File**
2022-01-24 13:09:55.822 +10:00 [INF] Setting key value for icon in registry
2022-01-24 13:09:55.848 +10:00 [INF] Current exe path : C:/Users/Dave/AppData/Local/Linkedin-Learning-Courses-Downloader/app-1.1.0/Linkedin-Learning-Courses-Downloader.exe
2022-01-24 13:09:55.848 +10:00 [INF] Key value for icon is set successfully
2022-01-24 13:09:55.849 +10:00 [INF] Restoring config file
2022-01-24 13:09:55.849 +10:00 [INF] No config file to restore is found
2022-01-24 13:09:55.998 +10:00 [INF] No Config is found
2022-01-24 13:09:56.414 +10:00 [INF] Checking for updates...
2022-01-24 13:09:58.016 +10:00 [INF] No updates detected.
2022-01-24 13:10:30.596 +10:00 [INF] Validating Input
2022-01-24 13:10:31.697 +10:00 [INF] Input Valid
2022-01-24 13:18:50.669 +10:00 [ERR] Unknown error occured
code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
no such table: cookies
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader()
   at LLCD.CourseExtractor.CookiesExtractor.ReadChromiumCookies(String profilePath)
   at LLCD.CourseExtractor.CookiesExtractor.ReadChromeCookies()
   at LLCD.CourseExtractor.Extractor.ExtractToken(Browser browser)
   at LLCD.DownloaderGUI.MainForm.btnExtractToken_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at LLCD.DownloaderGUI.Program.Main()

LOVE THIS SOFTWARE! By the way...

**Comment by ahmedayman4a** [comment]
Firstly, glad you liked my app.
The issue you described is now fixed with this commit cbe77a1d23b964b47b6aaab0ce69d7bddc3d44dd. Thanks for reporting the bug. Seems that chrome changed its cookies db location in a recent update which broke the extractor.
Did you face any other issues with v2.0? Do you think it is ready for release?
