### ISSUE TITLE
not working in linux

### ISSUE THREAD

**Issue by need4android-com** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#4]
When trying to run it in centos7 it's aborting with this error message:
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_InvariantCulture()
   at Serilog.Parsing.PropertyToken..ctor(System.String, System.String, System.String, System.Nullable`1<Serilog.Parsing.Alignment>, Serilog.Parsing.Destructuring, Int32)
   at Serilog.Parsing.MessageTemplateParser.ParsePropertyToken(Int32, System.String, Int32 ByRef)
   at Serilog.Parsing.MessageTemplateParser+<Tokenize>d__1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AddRange(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Collections.Generic.EnumerableHelpers.ToArray[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Linq.Enumerable.ToArray[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at Serilog.Events.MessageTemplate..ctor(System.String, System.Collections.Generic.IEnumerable`1<Serilog.Parsing.MessageTemplateToken>)
   at Serilog.Parsing.MessageTemplateParser.Parse(System.String)
   at Serilog.Formatting.Display.MessageTemplateTextFormatter..ctor(System.String, System.IFormatProvider)
   at Serilog.FileLoggerConfigurationExtensions.File(Serilog.Configuration.LoggerSinkConfiguration, System.String, Serilog.Events.LogEventLevel, System.String, System.IFormatProvider, System.Nullable`1<Int64>, Serilog.Core.LoggingLevelSwitch, Boolean, Boolean, System.Nullable`1<System.TimeSpan>, Serilog.RollingInterval, Boolean, System.Nullable`1<Int32>, System.Text.Encoding, Serilog.Sinks.File.FileLifecycleHooks)
   at LLCD.DownloaderTUI.Program+<Main>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[LLCD.DownloaderTUI.Program+<Main>d__1, Linkedin Learning Courses Downloader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<Main>d__1 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[LLCD.DownloaderTUI.Program+<Main>d__1, Linkedin Learning Courses Downloader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<Main>d__1 ByRef)
   at LLCD.DownloaderTUI.Program.Main(System.String[])
   at LLCD.DownloaderTUI.Program.<Main>(System.String[])
Aborted

**Comment by ahmedayman4a** [comment]
I don't have centos7 but I will try looking for this issue on google
