### ISSUE TITLE
[BUG] Video Name too long

### ISSUE THREAD

**Issue by aYip9394** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#51]
**Describe the bug**
If the video title is too long, it will not save the video and stop downloading at that video. Here is the course that I tried to download https://www.linkedin.com/learning/comptia-security-plus-sy0-601-cert-prep-4-identity-and-access-management-design-and-implementation/identification-authentication-authorization-and-accounting?autoplay=true&contextUrn=urn%3Ali%3AlyndaLearningPath%3A57bdd64992015ae4c0cb990e&resume=false&u=93946321. It will stop at 1.1 Identification, authentication, authorization, and accounting

**Operating System**
Windows 10

**Log File**
2022-07-01 21:29:07.500 -04:00 [INF] Restoring config file
2022-07-01 21:29:07.549 -04:00 [INF] No config file to restore is found
2022-07-01 21:29:08.139 -04:00 [INF] Acquired data from config
2022-07-01 21:29:08.527 -04:00 [INF] Checking for updates...
2022-07-01 21:29:08.940 -04:00 [INF] No updates detected.
2022-07-01 21:29:17.246 -04:00 [INF] Validating Input
2022-07-01 21:29:18.782 -04:00 [INF] Input Valid
2022-07-01 21:29:35.026 -04:00 [ERR] Failed to download video with title Identification, authentication, authorization, and accounting
System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Nuc\Downloads\CompTIA\CompTIA Security+ SY0-601\LinkedIn Videos\CompTIA Security+ (SY0-601) Cert Prep 4 Identity and Access Management Design and Implementation\02 - 1. Identification\01 - Identification, authentication, authorization, and accounting.srt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at LLCD.DownloaderGUI.DownloaderForm.<SaveSubtitles>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LLCD.DownloaderGUI.DownloaderForm.<>c__DisplayClass16_2.<<DownloadCourse>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at LLCD.CourseExtractor.Retry.<Do>d__3.MoveNext()
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Nuc\Downloads\CompTIA\CompTIA Security+ SY0-601\LinkedIn Videos\CompTIA Security+ (SY0-601) Cert Prep 4 Identity and Access Management Design and Implementation\02 - 1. Identification\01 - Identification, authentication, authorization, and accounting.srt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at LLCD.DownloaderGUI.DownloaderForm.<SaveSubtitles>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LLCD.DownloaderGUI.DownloaderForm.<>c__DisplayClass16_2.<<DownloadCourse>b__1>d.MoveNext()<---

2022-07-01 21:29:35.040 -04:00 [INF] Running Action on Error
2022-07-01 21:29:35.044 -04:00 [ERR] Trying again 1
2022-07-01 21:29:35.046 -04:00 [ERR] Failed to download video with title Identification, authentication, authorization, and accounting
System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Nuc\Downloads\CompTIA\CompTIA Security+ SY0-601\LinkedIn Videos\CompTIA Security+ (SY0-601) Cert Prep 4 Identity and Access Management Design and Implementation\02 - 1. Identification\01 - Identification, authentication, authorization, and accounting.srt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at LLCD.DownloaderGUI.DownloaderForm.<SaveSubtitles>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LLCD.DownloaderGUI.DownloaderForm.<>c__DisplayClass16_2.<<DownloadCourse>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at LLCD.CourseExtractor.Retry.<Do>d__3.MoveNext()
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Nuc\Downloads\CompTIA\CompTIA Security+ SY0-601\LinkedIn Videos\CompTIA Security+ (SY0-601) Cert Prep 4 Identity and Access Management Design and Implementation\02 - 1. Identification\01 - Identification, authentication, authorization, and accounting.srt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at LLCD.DownloaderGUI.DownloaderForm.<SaveSubtitles>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LLCD.DownloaderGUI.DownloaderForm.<>c__DisplayClass16_2.<<DownloadCourse>b__1>d.MoveNext()<---

2022-07-01 21:29:35.047 -04:00 [INF] Running Action on Error
2022-07-01 21:29:35.047 -04:00 [ERR] Trying again 2
2022-07-01 21:29:35.047 -04:00 [ERR] Failed to download video with title Identification, authentication, authorization, and accounting
System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Nuc\Downloads\CompTIA\CompTIA Security+ SY0-601\LinkedIn Videos\CompTIA Security+ (SY0-601) Cert Prep 4 Identity and Access Management Design and Implementation\02 - 1. Identification\01 - Identification, authentication, authorization, and accounting.srt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at LLCD.DownloaderGUI.DownloaderForm.<SaveSubtitles>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LLCD.DownloaderGUI.DownloaderForm.<>c__DisplayClass16_2.<<DownloadCourse>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at LLCD.CourseExtractor.Retry.<Do>d__3.MoveNext()
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Nuc\Downloads\CompTIA\CompTIA Security+ SY0-601\LinkedIn Videos\CompTIA Security+ (SY0-601) Cert Prep 4 Identity and Access Management Design and Implementation\02 - 1. Identification\01 - Identification, authentication, authorization, and accounting.srt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at LLCD.DownloaderGUI.DownloaderForm.<SaveSubtitles>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LLCD.DownloaderGUI.DownloaderForm.<>c__DisplayClass16_2.<<DownloadCourse>b__1>d.MoveNext()<---

2022-07-01 21:29:35.047 -04:00 [INF] Running Action on Error
2022-07-01 21:29:35.047 -04:00 [ERR] Trying again 3
2022-07-01 21:29:35.047 -04:00 [ERR] Failed to download video with title Identification, authentication, authorization, and accounting
System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Nuc\Downloads\CompTIA\CompTIA Security+ SY0-601\LinkedIn Videos\CompTIA Security+ (SY0-601) Cert Prep 4 Identity and Access Management Design and Implementation\02 - 1. Identification\01 - Identification, authentication, authorization, and accounting.srt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at LLCD.DownloaderGUI.DownloaderForm.<SaveSubtitles>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LLCD.DownloaderGUI.DownloaderForm.<>c__DisplayClass16_2.<<DownloadCourse>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at LLCD.CourseExtractor.Retry.<Do>d__3.MoveNext()
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Nuc\Downloads\CompTIA\CompTIA Security+ SY0-601\LinkedIn Videos\CompTIA Security+ (SY0-601) Cert Prep 4 Identity and Access Management Design and Implementation\02 - 1. Identification\01 - Identification, authentication, authorization, and accounting.srt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at LLCD.DownloaderGUI.DownloaderForm.<SaveSubtitles>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LLCD.DownloaderGUI.DownloaderForm.<>c__DisplayClass16_2.<<DownloadCourse>b__1>d.MoveNext()<---

2022-07-01 21:29:35.048 -04:00 [INF] Running Action on Error
2022-07-01 21:29:35.048 -04:00 [ERR] Trying again 4
2022-07-01 21:29:35.048 -04:00 [ERR] Failed to download video with title Identification, authentication, authorization, and accounting
System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Nuc\Downloads\CompTIA\CompTIA Security+ SY0-601\LinkedIn Videos\CompTIA Security+ (SY0-601) Cert Prep 4 Identity and Access Management Design and Implementation\02 - 1. Identification\01 - Identification, authentication, authorization, and accounting.srt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at LLCD.DownloaderGUI.DownloaderForm.<SaveSubtitles>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LLCD.DownloaderGUI.DownloaderForm.<>c__DisplayClass16_2.<<DownloadCourse>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at LLCD.CourseExtractor.Retry.<Do>d__3.MoveNext()
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Nuc\Downloads\CompTIA\CompTIA Security+ SY0-601\LinkedIn Videos\CompTIA Security+ (SY0-601) Cert Prep 4 Identity and Access Management Design and Implementation\02 - 1. Identification\01 - Identification, authentication, authorization, and accounting.srt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at LLCD.DownloaderGUI.DownloaderForm.<SaveSubtitles>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LLCD.DownloaderGUI.DownloaderForm.<>c__DisplayClass16_2.<<DownloadCourse>b__1>d.MoveNext()<---

2022-07-01 21:29:35.048 -04:00 [INF] Running Action on Error
2022-07-01 21:29:35.048 -04:00 [ERR] Trying again 5
2022-07-01 21:29:35.048 -04:00 [FTL] Error occured 5 times without being resolved
2022-07-01 21:29:35.048 -04:00 [INF] Running action on fatal

**Comment by ahmedayman4a** [comment]
Will be fixed with v1.3

**Comment by ahmedayman4a** [comment]
For now, download the courses to a shorter path, like for example D:\MyCourses

**Comment by aryamo** [comment]
https://www.linkedin.com/learning/building-an-iso-27001-compliant-cybersecurity-program-the-annex-a-controls?u=95230681

this course doesn't work even in C:\
